- images/substrate/Dockerfile
Since substrate only uses the podman socket, we don't need all these other deps. Removing them speeds up the build and reduces possible sources of complications.
> substrate: skip podman deps we can avoid

- images/vscode-server/Dockerfile
- images/vscode-server/entrypoint.sh
The goal for this daemon/service is to be an "already set up" dev environment for improving (and live editing) substrate and SubstrateOS
> vscode-server: add go and cue extensions

- images/bridge2/cmd/bridge/main.go
- images/bridge2/tracks/tracks.go
- images/bridge2/ui/sidebar.js
Instead of just listing the sessions by id, open the session files to get the start time as well. Depending on speed, some caching might be helpful here, or a file watcher to only load on-demand.
Fixes #48
> bridge2: show session list with dates instead of ids

- defs/bridge2.cue
- images/bridge2/cmd/bridge/main.go
Uses `BRIDGE_URL_BASE_PATH` set in Cue to configure
the URL prefix, and parses the `PORT` environment
variable.
Fixes #101
> bridge2: read config from the environment

- images/bridge2/ui/session.html
- images/bridge2/webrtc/js/localmedia.js
The bridge code was setting `videoEnabled = false`
but in `LocalMedia` we need to:
1) use the video/audio enabled to only request the
specified devices
2) pass in initial values for properties so that
they're taken into account on the first call to
`updateDevices()`
Fixes #107
> bridge2: only require microphone permissions

- dev.sh
This made it hard to know when the reload had finished. If you want the old functionality, use system-reload-follow or srf.
> chore: switch systemd-reload to not tail logs

- images/bridge2/tracks/tracks.go
- images/bridge2/ui/session.html
- images/bridge2/ui/session.js
Convert event time offsets to a JS Date for
display.
Sorts all events by time so that events from
multiple tracks are merged in-order.
Fixes #122
> bridge2: display timestamps correctly

- images/bridge2/cmd/bridge/main.go
The http ServeMux pattern `/` any requests that
aren't already assigned, so this would redirect
other unknown paths to `/sessions` and create a
new session. So on page loads, extra requests
like `/favicon.ico` would trigger a new session
in the background.
This only redirects when the path is just `/`.
Additionally we could have the `GET /session`
index not create a session, and leave that to a JS
POST call on load, but refining the redirect is
good enough for the moment.
Fixes #123
> bridge2: only redirect requests for `/`

- images/bridge2/cmd/bridge/main.go
- images/bridge2/vad/vad.go
Clamping the VAD start time to the beginning of
the track should happen only when it has detected
activity. This was emitting extra "activity"
events when there wasn't a valid start time,
leading to duplicated transcription from the
beginning of the track.
Fixes #135
> bridge2: clamp VAD start after checking for 0

- images/substrate/provisioner/docker/status.go
- images/substrate/provisioner/podman/status.go
When a container crashes on boot we see the error: "dial tcp: lookup xxx.xxx.xxx.xxx: no such host". Detect this type of error and give up waiting for it.
> fix: give up when a container crashes on boot

- defs/bb.cue
- defs/defs.cue
- defs/faster-whisper.cue
- defs/seamlessm4t.cue
Fix faster-whisper and seamlessm4t tests to run via substrate gateway.
These tests didn't work directly against the substrate gateway before because the generated docker compose yaml was missing proper network configuration for tests.
> dev: add run translator and transcribe tests to bb

- images/bridge/pkg/router/types.go
- images/bridge/pkg/transcriber/transcriber.go
- images/bridge2/transcribe/transcribe.go
- images/faster-whisper/Dockerfile
- images/faster-whisper/app.py
- images/tests/transcriber/test.go
Also switch faster-whisper to using its internal audio decoding logic.
This also fixes a spurious failure in the faster-whisper transcribe test where we weren't resampling the decoded test.ogg file properly. This didn't affect actual behavior because the .ogg file is decoded at 48000 but bridge2 sends audio as 16000 wav.
The result is slightly more correct and uses fewer deps.
> chore: pass through a mime_type for audio

- images/substrate/activityspec/service.go
The URL RFC says ( and ) are acceptable for use in paths. It does not list [ and ] as acceptable. So switch to parens.
> refactor: substrate activityspec should match RFC

- images/bridge2/cmd/bridge/main.go
- images/bridge2/webrtc/trackstreamer/trackstreamer.go
Return an error when the track audio reaches an EOF error. This was not exiting
the audio read loop and continuing to process empty audio chunks for the track,
which led to high CPU usage.
Fixes #150
> bridge2: terminate audio loop on EOF

- images/bridge2/cmd/bridge/main.go
- images/bridge2/ui/session.html
- images/bridge2/ui/sidebar.js
- images/bridge2/ui/topbar.js
It's not always appropriate to start a new session
when loading the index, so move new session
creation to a new path. Adds a button to the index
to start a session, or the user can select a
previous session from the sidebar.
Some other small UI updates to highlight the
active session in the sidebar, and show the
session time instead of "session1" header.
Also adds a timeout for refreshing the list of
sessions when there is not active session, or
there are no new events on the current session.
Fixes #161
> bridge2: don't start new session on index

- images/bridge2/ui/session.html
By setting the height of the right-pane to the
screen height the session contents will scroll
without scrolling the navigation areas.
Fixes #147
> bridge2: fix height of main content area

- defs/bridge2.cue
- images/bridge2/cmd/bridge/main.go
- images/bridge2/translate/translate.go
- images/bridge2/ui/session.html
- images/bridge2/ui/session.js
Adds an agent to the bridge2 process that watches
for transcription events and sends them to the
translator service.
#63 
UI is just a quick hack right now to make sure it's getting some sensible data. Though I guess if the other stuff seems alright, I could commit the backend with a separate PR for the UI the way it was split out in #84.
Looking at the previous bridge code, it parsed translator environment variables containing the language name and other options. I'm not sure if we want to keep that config at the environment level for what target languages to support. Or #67 had some discussion about adding target languages per-session.
> bridge2: add translator agent

- defs/files.cue
- images/files/main.go
There was a formatting error in files.cue, and
re-ran `go fmt` to remove the broken "assets"
import from the `files` service.
> fix: some minor errors from #176

- defs/bridge2.cue
- images/bridge2/assistant/assistant.go
- images/bridge2/assistant/assistant_test.go
- images/bridge2/assistant/chat.go
- images/bridge2/bridgetest/bridgetest.go
- images/bridge2/cmd/bridge/main.go
- images/bridge2/transcribe/transcribe.go
- images/bridge2/ui/session.html
- images/bridge2/ui/session.js
Adds a basic assistant agent. Right now configuration is mostly hard-coded to include the "bridge" assistant. More could be added to the map, but we can address runtime configuration in #190.
It looks for the assistant name anywhere in the message and passes just the current message to the configured URL using the OpenAI API.
Fixes #64
> bridge2: assistant agent

- images/bridge2/assistant/assistant.go
- images/bridge2/assistant/assistant_test.go
- images/bridge2/assistant/prompt_fs_sync.go
- images/bridge2/assistant/prompt_fs_sync_test.go
- images/bridge2/assistant/prompts/complete.tmpl
- images/bridge2/assistant/prompts/prompts.go
- images/bridge2/cmd/bridge/main.go
- images/bridge2/tracks/tracks.go
- images/bridge2/ui/commands.js
- images/bridge2/ui/session.html
- images/bridge2/ui/substrate-r0.js
Enable adding & removing per-session assistants.
To add an assistant we record an event with the name and system prompt, which
then adds that client an agent listening to the session. New events can change
the prompt, or by setting it to an empty string we disable that assistant.
By recording the system prompt as an event we retain a record of the changes
which might be helpful for reviewing the session history.
Prompts are synced with plain text files in a sub-folder `assistant` under the session's storage directory to allow for editing on the filesystem.
> bridge: add/remove assistants

- images/bridge2/ui/session.html
A routing change led to having a trailing slash
on the `/sessions/` index page, but computing
the WebSocket URL assumed that it could append
`/data`. This trims the trailing slash so that
the WebSocket URL is correct.
> bridge2: fix bug with double-slash in WS URL

- defs/tool-call.cue
- images/chromestage/cmd/chromestage/main.go
- images/substrate/cmd/main.go
- images/tool-call/js/commands.js
- images/tool-call/js/embed.go
- images/tool-call/js/suggest.js
- images/tool-call/main.go
Adds a JavaScript client for the `tool-call` service.
Exposes `commands.js` with the core clients for using commands from JavaScript,
along with `suggest.js` with a wrapper to the tool-call suggest command which
handles sending the command index, and optionally invoking the command from the
response.
> tool-call: add JS client code

- images/substrate/db/db.go
When we switched resourcedirs to being container images, the mount data structure switched from being a list to being an object. This means we can't deserialize the ServiceSpawnResponse in past events.
So switch to loading it as any. This works for our needs and keeps things both simple and flexible.
> fix: Decode Event.Response as any

- os/src/config/overlay.d/50substrateos/etc/caddy/Caddyfile
Also having it in the Caddyfile actually breaks CORS because the headers are present twice.
> fix: cors should be handled by substrate gateway

- defs/bridge.cue
- images/bridge/assistant/assistant.go
- images/bridge/assistant/tools/agent.go
- images/bridge/cmd/bridge/main.go
- images/bridge/diarize/diarize.go
- images/bridge/go.mod
- images/bridge/go.sum
- images/bridge/tracks/tracks.go
- images/bridge/transcribe/transcribe.go
- images/bridge/translate/translate.go
- images/bridge/vad/vad.go
- pkg/toolkit/event/event.go
Consume the event stream to drive bridge.
Currently, this disables actually triggering events on the bridge
`record<EventType>` calls, and instead waits for the event to come through on
the stream to trigger handlers.
> bridge: consume events

- images/events/cmd/events/main.go
- images/events/units/reaction.go
I started testing this out as a simple way to
prototype reactions. The input is the same
as `events:write` (though right now limited to 1
reaction) which makes it easy to save by just
updating the command to write it when you're done.
But instead if runs and returns the results of the
reaction.
This made it fairly easy to iterate on the
reaction for combining transcription words that we
were looking at earlier.
> add "events:try-reaction" command

- images/webrtc-stream/cmd/webrtc-stream/main.go
Pass the event prefix to use when playing back events. Also set the buffer size back to 4kb. We can tune more, but I had just bumped this down while debugging the crashes.
> webrtc-stream: fix stream event prefix

- images/events/store/view.go
- pkg/toolkit/event/query.go
Make Criteria fields not pointers to help with NPE errors using event queries unmarshalled from JSON.
While we could add addtional nil checks, or other intialization when unmarshalling, based on the way these fields are used it seems simpler remove the pointers in order to avoid the issue.
> fix unmarshalling event query

- pkg/navigator/parser.js
The navigator grammar didn't include support for negative signs on numbers.
> navigator: parse negative numbers

- pkg/bridge-reactions/bridge-audio.md
- pkg/synthesizer/blocks.js
- pkg/synthesizer/blocks/transcript.renkon.js
Currently includes a Markdown file outlining the steps to set up reactions for transcribing audio records emitted from the webrtc-stream service.
Made a couple changes to transcript.renkon.js to allow some missing fields that are not currently populated.
The event prefix is currently set to `bridge-demo`, I tried using a prefix like `bridge/demo` with a slash, but had run into an issue with that in the `webrtc-stream` service. Escaping it in the URL like:
```
https://substrate-a3a1.local/webrtc-stream;event_prefix=bridge%2Fdemo;sessions=sp-01JTH6QEYQ022KPQXS4T2FP776/
```
led to an error trying to connect to its own endpoint to handle the webrtc connections:
```
INFO http at url=http://[::]:8080
INFO connecting to local peer url="ws://localhost:8080/webrtc-stream;event_prefix=bridge%2Fdemo; …
```
> steps for setting up bridge audio processing

- pkg/bridge-reactions/bridge-text-pipeline-combined.md
- pkg/bridge-reactions/bridge-text-pipeline.md
Markdown documents describing setting up reactions to provide the text-based reactions for bridge:
* translation
* assistants
* tool calling
It’s currently described in two documents which are mostly duplicated in terms of the actual code: 
`bridge-text-pipeline.md`: this was my initial prototype and contains more explanation of each step, however it has drifted from the current schema & syntax in a few places
`bridge-text-pipeline-combined.md`: this was a subsequent attempt to summarize the previous version into a few statements to copy/paste into Navigator. The syntax here has been updated more recently, though lacks the intermediary descriptions of the steps since they were combined.
> bridge text reactions
